#!/usr/bin/env python

import time
import rospy

from std_msgs.msg import *
i=0; r=0; g=0; b=0;

## Cycle through RGB colorspace (code hijacked from arduino RGB LED demo)
def update_color():
  global i,r,g,b
  i=(i+1)%768
  if i < 256:
    r = (255-i)/255.0
    g = (i)/255.0
    b = 0
  elif i<512:
    r = 0
    g = (512-i)/255.0
    b = (i-256)/255.0
  elif i<768:
    r = (i-512)/255.0
    g = 0
    b = (768-i)/255.0


if __name__=='__main__':
  global r, g, b
  rospy.init_node('set_speed', anonymous=True)
  color_pub = rospy.Publisher('/set_color', ColorRGBA)

  while True:
    update_color();
    color_pub.publish(ColorRGBA(r,g,b,0))
    time.sleep(0.01)


